rtmp-server:
  image: itmadublin/nginx.rtmp
  ports:
    - "1935:1935"
  environment:
    # env var beginning with "streamkey_ will be translated into nginx push commands"
    - streamkey_youtube=rtmp://a.rtmp.youtube.com/live2/2f9x-s9dt-t7qe-d0tx
    - streamkey_facebook=rtmp://rtmp-api.facebook.com:80/rtmp/10154731817267569?ds=1&s_l=1&a=AThvodZBtd3uo4Zm

