rtmp-server:
  image: itmadublin/nginx.rtmp
  ports:
    - "1935:1935"
  environment:
    # env var beginning with "streamkey_ will be translated into nginx push commands"
    - streamkey_youtube=rtmp://a.rtmp.youtube.com/live2/e8u9-z3wa-g0k1-51e5


